-- Migração 011: cadastro dos Mobs (monstros) do jogo, extraídos de
-- https://ninonline.fandom.com/wiki/Category:Mob (categoria completa, 145
-- páginas de mob individuais — a lista "147" da categoria inclui a própria
-- página-índice "Mob" e uma categoria-filha, que não são mobs em si).
--
-- Escopo, conforme pedido: TODOS os mobs da wiki, incluindo os drops de
-- cada um, e criando automaticamente na tabela `items` os itens de drop
-- que ainda não existem no catálogo (type = 'item_mob').
--
-- Fonte dos dados: infobox {{Infobox/Monster|...}} de cada página (level,
-- health, location, damage, type, experience, special_ability, drops) e,
-- quando presente, a tabela "Loot List" da página (mais precisa que o
-- campo de texto livre `drops` do infobox).
--
-- Classificação (`category`):
--   - 'boss': mobs listados nas categorias Category:BOSS / Category:Boss
--     da wiki, OU cujo campo `type` do infobox contém a palavra "Boss"
--     (ex.: "Yokai (Boss)" pra Ongaku, Kikkumaru, Jirou).
--   - 'enfurecido': mobs cujo nome começa com "Angry", "Enraged" ou "Mad"
--     (não existe categoria própria na wiki pra isso, então foi um
--     heurística por nome).
--   - 'regular': todo o resto.
--
-- Lacunas de dados: ~26 mobs não têm infobox completo na própria wiki
-- (páginas-stub, principalmente "Elite" da seção de Bestiário/mobs raros
-- e alguns "Not recorded"/"Information needed"). Pra esses, `level` e
-- `hp` caem no default da coluna (1) em vez de ficar null, já que as
-- colunas são NOT NULL — edite manualmente no Admin quando o dado
-- correto for descoberto/confirmado no jogo.
--
-- Imagens (`image_url`) ficam propositalmente null — conforme combinado,
-- o upload das imagens de mob é manual, feito depois pelo admin.
--
-- Itens de drop criados automaticamente (tabela items, type='item_mob')
-- não têm descrição nem imagem — preencha depois no Admin. O
-- "on conflict (lower(name)) do nothing" abaixo garante que reexecutar
-- essa migração nunca sobrescreve um item que você já editou manualmente
-- (nome, descrição, imagem, ou mesmo um type diferente que você tenha
-- corrigido).
--
-- Taxas de drop (`drop_rate`): quando a página tem uma "Loot List"
-- estruturada, o percentual vem direto dela. Quando só há o campo de
-- texto livre (ex.: "Common", "<5%", "Rare"), foi convertido por uma
-- tabela aproximada (Common=50%, Uncommon=20%, Rare=5%, "<1%"=0.5%,
-- "<5%"=3%); quando não dá pra inferir nada, `drop_rate` fica null.

create unique index if not exists mobs_name_unique_idx on mobs (lower(name));

-- ---------------------------------------------------------------
-- Itens de drop (cria os que faltam no catálogo)
-- ---------------------------------------------------------------
insert into items (name, type) values
  ('Adamantine Staff', 'item_mob'),
  ('Adamantine Sword', 'item_mob'),
  ('Ant Feelers', 'item_mob'),
  ('Arm Bandage', 'item_mob'),
  ('Asarihanma', 'item_mob'),
  ('Bamboo Hat', 'item_mob'),
  ('Bat Wings', 'item_mob'),
  ('Beaded Necklace', 'item_mob'),
  ('Bear Paw', 'item_mob'),
  ('Big Scarab Shell', 'item_mob'),
  ('Big Scarab Shells', 'item_mob'),
  ('Black Arm Bandages', 'item_mob'),
  ('Black Backpack', 'item_mob'),
  ('Black Bandit Blade', 'item_mob'),
  ('Black Bandit Mask', 'item_mob'),
  ('Black Bandit Pants', 'item_mob'),
  ('Black Bandit Shoes', 'item_mob'),
  ('Black Bear Hood', 'item_mob'),
  ('Black Bear Paws', 'item_mob'),
  ('Black Folded Pants', 'item_mob'),
  ('Black Giant Folding Fan', 'item_mob'),
  ('Black Masked Top', 'item_mob'),
  ('Blank Scroll', 'item_mob'),
  ('Blank Scroll.', 'item_mob'),
  ('Blank Scrolls', 'item_mob'),
  ('Blood Engine', 'item_mob'),
  ('Blood Iron Fan', 'item_mob'),
  ('Blood Vial', 'item_mob'),
  ('Blue Bandit Mask', 'item_mob'),
  ('Blue Folded Pants', 'item_mob'),
  ('Blue Masked Top', 'item_mob'),
  ('Boar Tusk', 'item_mob'),
  ('Brownbear Paws', 'item_mob'),
  ('Canine Fang', 'item_mob'),
  ('Carrot', 'item_mob'),
  ('Chest Bandages', 'item_mob'),
  ('Cocoon', 'item_mob'),
  ('Crystal Fan', 'item_mob'),
  ('Crystal Pipe', 'item_mob'),
  ('Dark Barbarian Cloak Recipe', 'item_mob'),
  ('Dark Fur', 'item_mob'),
  ('Dark Scythes', 'item_mob'),
  ('Dark Veiled Sakkat Recipe', 'item_mob'),
  ('Demon Claws', 'item_mob'),
  ('DNA Sample', 'item_mob'),
  ('Double Arm Bandages', 'item_mob'),
  ('Dragonfly wings', 'item_mob'),
  ('Egg', 'item_mob'),
  ('Eggs', 'item_mob'),
  ('Finger', 'item_mob'),
  ('Fox Fur', 'item_mob'),
  ('Gas Mask', 'item_mob'),
  ('Gloves Knuckle', 'item_mob'),
  ('Gray Bear Paw', 'item_mob'),
  ('Great Grandfather''s Muramasa', 'item_mob'),
  ('Green Folded Pants', 'item_mob'),
  ('Green Striped Bucket Hat', 'item_mob'),
  ('Hanging Sakkat', 'item_mob'),
  ('Hawk Feather', 'item_mob'),
  ('Hawk Talon', 'item_mob'),
  ('Hohuto Sphere II', 'item_mob'),
  ('Hokuto Sphere I', 'item_mob'),
  ('Hokuto Sphere II', 'item_mob'),
  ('Hokuto Sphere IV', 'item_mob'),
  ('Hokutso Sphere III', 'item_mob'),
  ('Honey Comb', 'item_mob'),
  ('Hunters Warglaive', 'item_mob'),
  ('Insect Wing', 'item_mob'),
  ('Insect Wings', 'item_mob'),
  ('Iron Piece', 'item_mob'),
  ('Iron Prison Key', 'item_mob'),
  ('Iron Scythe', 'item_mob'),
  ('Jakuma', 'item_mob'),
  ('Kazaruu Recipe', 'item_mob'),
  ('Kotsuzui Tanto', 'item_mob'),
  ('Large Scarab Pincers', 'item_mob'),
  ('Leather', 'item_mob'),
  ('Leech Fang', 'item_mob'),
  ('Leech Shell', 'item_mob'),
  ('Leg Bandage', 'item_mob'),
  ('Mizukane?', 'item_mob'),
  ('Mobster Ring', 'item_mob'),
  ('Moth Wings', 'item_mob'),
  ('Nitoryu Recipe', 'item_mob'),
  ('Old Tengu Mask', 'item_mob'),
  ('Orange Striped Bucket Hat', 'item_mob'),
  ('Oriental Fan', 'item_mob'),
  ('Penguin Beak', 'item_mob'),
  ('Prowler Pants', 'item_mob'),
  ('Puppet head', 'item_mob'),
  ('Puppet limb', 'item_mob'),
  ('Puppet string', 'item_mob'),
  ('Rabbit Paw', 'item_mob'),
  ('Rabid Hide', 'item_mob'),
  ('Raccoon Tail', 'item_mob'),
  ('Raging Bandit Pants', 'item_mob'),
  ('Raging Hermit Pants', 'item_mob'),
  ('Raging Hermit Shirt', 'item_mob'),
  ('Random Tools Pack', 'item_mob'),
  ('Rat Tail', 'item_mob'),
  ('Red Backpack', 'item_mob'),
  ('Red Fighter Pants', 'item_mob'),
  ('Red Folded Pants', 'item_mob'),
  ('Red Poncho', 'item_mob'),
  ('Red Scarf', 'item_mob'),
  ('Red Striped Bucket Hat', 'item_mob'),
  ('Red Twinfall Scarf Recipe', 'item_mob'),
  ('Reinforced Bo Staff', 'item_mob'),
  ('Religious Katana', 'item_mob'),
  ('Romaji Bandit Pants', 'item_mob'),
  ('Sashed Baggy Pants', 'item_mob'),
  ('Scarab Shell', 'item_mob'),
  ('Scorpion Tail', 'item_mob'),
  ('Seathorn Pipe', 'item_mob'),
  ('See the Drops table below', 'item_mob'),
  ('Seji no Hani', 'item_mob'),
  ('Shirokata', 'item_mob'),
  ('Silk', 'item_mob'),
  ('Snake Belt', 'item_mob'),
  ('Snake Inner Kimono', 'item_mob'),
  ('Snake Rope Belt', 'item_mob'),
  ('Snake Venom', 'item_mob'),
  ('Spider Eggs', 'item_mob'),
  ('Straw Hat', 'item_mob'),
  ('Sukarabe Omo', 'item_mob'),
  ('Tales of a Gutsy Ninja', 'item_mob'),
  ('Tan Barbarian Cloak Recipe', 'item_mob'),
  ('Tanned Leather', 'item_mob'),
  ('Teeth', 'item_mob'),
  ('Tengai Hat', 'item_mob'),
  ('Tengu Mask', 'item_mob'),
  ('Tiger Fur', 'item_mob'),
  ('Tonfa', 'item_mob'),
  ('Tunneler Tongue', 'item_mob'),
  ('Twin Blades', 'item_mob'),
  ('Twin Fangs', 'item_mob'),
  ('Undead Charm', 'item_mob'),
  ('Venom', 'item_mob'),
  ('Vigilante Bandana Mask Recipe', 'item_mob'),
  ('White Bandit Mask', 'item_mob'),
  ('White Fighter Pants', 'item_mob'),
  ('White Folded Pants', 'item_mob'),
  ('White Straw Hat', 'item_mob'),
  ('Whiter Fighter Pants', 'item_mob'),
  ('Winter Scarf', 'item_mob'),
  ('Wolf Fur', 'item_mob'),
  ('Wooden Tonfa', 'item_mob'),
  ('Yamazaru', 'item_mob')
on conflict (lower(name)) do nothing;

-- ---------------------------------------------------------------
-- Mobs
-- ---------------------------------------------------------------
insert into mobs (name, category, level, location_note, hp, damage_min, damage_max, combat_type, xp_reward, description, special_abilities) values
  ('Big Scarabs', 'regular', 23, 'Secret Desert Cavern', 155, 39, 39, 'agressivo', 172, 'Big Scarabs are a Level 23 mobs which currently inhabit various locations around the Sand Village, most notably Secret Desert Cavern.
* Attacks (moves) they are using:
** Basic Attack - 39 physical damage
It has been noted that it is a aggresive-type monster that will attack and follow you once you get in it''s range. Upon defeating this Monster, you receive 172xp (258 blessing).', '{}'),
  ('Bear', 'regular', 36, 'South of Leaf Village', 300, 94, 94, 'agressivo', 266, 'Bears are a Level 36 mob which currently inhabit various locations around the Leaf Village, most notably on the south of the village They are attributed really high damage and health but they are slow, because of this you can easily get past them or kill them by kiting around  them.', '{"Mountain Crash"}'),
  ('Alpha Wolf', 'regular', 43, 'Lake Stasis - Snowy Path', 1100, 97, 97, 'agressivo', 436, 'Alpha Wolfs  possess status affects attributed to their physical attacks, this status effect is "Bleed I "
it deals 2 dmg for 20 second.', '{"Bite","Body Flicker"}'),
  ('Cursed Host', 'regular', 38, 'Cursed Caves', 38, 38, 38, 'agressivo', 38, 'Cursed Host are level 40 and 38 monsters that currently inhabit Rocky Caves map (Danger Zone).', '{"Body Flicker"}'),
  ('Bee', 'regular', 26, 'Maps near Takumi village and Kinsen Quarters', 155, 44, 44, 'passivo', 200, 'Bee is Level 26 monster which currently inhabit areas near the Takumi village and Kinsen Quarters or near Akatsuki Base', '{}'),
  ('Bee Hive', 'regular', 26, 'Near Tanzaku Quarters and Takumi village.', 500, 5, 5, 'passivo', 8, 'Bee Hive is an special monster which can''t move and deals 5 dmg to attackers.It has 100% chance to drop honey comb.', '{"Can''t move"}'),
  ('Chei', 'boss', 47, 'Lake Stasis', 3480, 99, 99, 'agressivo', 3200, 'Chei is Reain''s bodyguard who is a master of Taijutsu. Her jutsus perfectly match with Reain''s skills because she uses specific skills that stun the opponent. Which allows Reain to calmly eliminate uninvited guest.', '{"Ground Shattering Kick","Great Fireball","Body Flicker ( 21 tiles distance )","Whirlwind Kick","Breaking Kick","Substitution Technique"}'),
  ('Blood Puppet', 'regular', 51, 'Blood Puppet Factory', 1200, 245, 245, 'passivo', 0, 'A humanoid puppet monster with mind of it''s own.', '{}'),
  ('Ant', 'regular', 3, '3 Way Road Split/Bloody Pond', 20, 7, 7, 'passivo', 20, 'Ants are Level 5 monsters which currently inhabit various locations around the Mist village, most notably on 3 Way Road Split and Bloody Pond.', '{}'),
  ('Boar', 'regular', 13, 'Misty Hides / Land of Water Port', 85, 26, 26, 'agressivo', 97, 'Boars are a level 13 monster which lives in an area close to the Mist Village called Misty Hides and also at the Land of Water Port.', '{}'),
  ('Black Boar', 'regular', 17, 'Misty Hides / Land of Water Port', 120, 44, 44, 'agressivo', 127, 'Black Boars are a level 17 monster which lives in an area close to the Mist Village called Misty Hides and the Land of Water Port, similar to normal boars, only difference being their black fur.', '{}'),
  ('Dark Monkey King', 'boss', 57, 'Valley of the End (Leaf war zone)', 1, 781, 781, 'agressivo', 30000, 'The Dark Monkey King is a passive boss type monster found in the Valley of the End south of the Leaf Village. It''s a blackened version of the Monkey King summon.', '{"Whirlwind Kick","Breaking Kick"}'),
  ('Admiral Mitsuhide', 'boss', 60, 'Iron Tower', 72000, 768, 768, 'agressivo', 0, 'Admiral Mitsuhide is a level 60 boss. Considered as most difficult boss in game. He is located in the Iron Tower area, tower located in the most northern part of the Land Of Iron.', '{"Flicker","Metal Chain Technique","Dance of the Ronin","Crescent Moon Beheading"}'),
  ('Bear Hermit', 'boss', 30, 'Bear Hermit Cave', 16000, null, null, 'agressivo', 16000, null, '{}'),
  ('Bat', 'boss', 29, 'Hyoketsu Cave Entrance, Hyoketsu Prison', 290, null, null, 'agressivo', 180, null, '{}'),
  ('Crystal Slug', 'regular', 45, 'Crystal Beach Cave', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Daimaru', 'boss', 25, 'Level 20 Arc', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Captain Midora', 'boss', 58, 'Land of Iron', 38069, 40, 40, 'agressivo', 21750, null, '{}'),
  ('Blight Leech', 'regular', 20, 'Crystal Beach Cave', 175, 11, 11, 'agressivo', 150, null, '{}'),
  ('Crimson Leech', 'regular', 21, 'Crystal Beach Cave', 180, 12, 12, 'agressivo', 157, null, '{}'),
  ('Angry Hawk', 'enfurecido', 39, 'Level 30 story arc (see Story Lines)', 1625, 19, 19, 'agressivo', 0, null, '{}'),
  ('Bad Raccoon Bandit', 'regular', 1, 'Level 30 story arc (see Story Lines)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Big Scorpion', 'regular', 10, 'Desert Palms, Howling Canyon', 165, 18, 18, 'agressivo', 370, 'In combat it attacks at a range of 5 and respawns every 300 seconds. It has no special jutsu.', '{}'),
  ('Black Bear', 'regular', 1, 'Forest Near the Ledge', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Crab', 'regular', 21, 'Coral Walk, Ship', 150, 8, 8, 'passivo', 0, null, '{}'),
  ('Crazy Spider', 'regular', 10, 'Mountain Peak, Moist Plains, Lake Bell, Near the Valley', 160, 18, 18, 'agressivo', 370, 'In combat it attacks at a range of 5 and respawns every 300 seconds. It has no special jutsu.', '{}'),
  ('Chochin', 'regular', 62, 'Land of Spirits', 1400, 18, 18, 'agressivo', 465, 'The Chochin is a hostile yokai found in the Land of Spirits, twisted by the dark influence spreading through the spirit realm.', '{}'),
  ('Bakezori', 'regular', 61, 'Land of Spirits', 1350, 18, 18, 'agressivo', 457, 'The Bakezori is a hostile yokai found in the Land of Spirits, twisted by the dark influence spreading through the spirit realm.', '{}'),
  ('Armed Tengu Guard', 'regular', 69, 'Land of Spirits', 1800, 21, 21, 'agressivo', 517, 'The Armed Tengu Guard is a hostile Level 69 tengu yokai found in the Land of Spirits, a stronger variant of the Tengu Guard.', '{}'),
  ('Black Oni', 'regular', 69, 'Land of Spirits', 1700, 20, 20, 'agressivo', 517, 'The Black Oni is a hostile Level 69 oni yokai found in the Land of Spirits. It roams alongside the Blue Oni and the far stronger Red Oni.', '{}'),
  ('Blue Oni', 'regular', 68, 'Land of Spirits', 1600, 20, 20, 'agressivo', 510, 'The Blue Oni is a hostile Level 68 oni yokai found in the Land of Spirits. It roams alongside the Black Oni and the far stronger Red Oni.', '{}'),
  ('Brown Betobeto', 'regular', 1, 'Spiritevil Falls, Land of Spirits', 1, null, null, 'agressivo', 0, 'The Brown Betobeto is a hostile yokai found at Spiritevil Falls in the Land of Spirits.', '{}'),
  ('Angry Moth', 'boss', 1, 'Not yet confirmed', 1, null, null, 'agressivo', 0, 'The Angry Moth is a large mini boss version of the Moths.', '{}'),
  ('Big Snake', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Big Snake is an entry in the in-game Bestiary.', '{}'),
  ('Blue Crab', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Blue Crab is an entry in the in-game Bestiary.', '{}'),
  ('Desert Coyote', 'regular', 9, 'West Desert Valley', 60, 18, 18, 'passivo', 67, 'Desert Coyotes are a Level 9 MOBs which currently inhabit various locations around the Sand Village, most notably on the north of the village.', '{}'),
  ('Guren', 'boss', 1, null, 1, null, null, 'agressivo', 0, 'Guren is one of the Daimyo''s bodyguards, along with Gafuki and resides in Takumi Village with him.', '{}'),
  ('Gafuki', 'boss', 40, 'Takumi Village', 8900, 61, 61, 'agressivo', 16000, 'Gafuki is one of Daimyo''s guard dogs along with Guren.', '{"Wild Slashes","Body Flicker","Mud River","Shockwave slash","Substitution Technique"}'),
  ('Glacier Bear', 'regular', 37, 'Cold Cave, Chilling Inner Cave', 2000, 149, 149, 'agressivo', 0, 'Glacier Bears are a Level 37 Mob which currently inhabit Cold cave west of the Ledge.', '{"Body Flicker Technique"}'),
  ('Hawk', 'regular', 34, 'Toad Mountain Passage', 330, 78, 78, 'passivo', 254, 'Hawks are level 34 mobs. They take places around Toad Village.', '{"Body Flicker"}'),
  ('Hornet', 'regular', 28, 'Maps near Takumi Village and Tanzaku Quarters.', 155, 48, 48, 'agressivo', 226, 'Hornets are Level 28 monsters which currently inhabit areas near the Takumi Village and Tanzaku Quarters.', '{}'),
  ('Hebimaru', 'boss', 50, 'Hebimaru''s Lair', 3000, null, null, 'agressivo', 0, 'Hebimaru is BOSS-type enemy created by mad scientist Houo....Orochimaru.', '{"Bite","Hebimaru Venom","Poison Breath","Summon Hebimaru Spawns."}'),
  ('Dragonfly', 'regular', 5, 'Big Slope / By The River / Land of Water Bounty Station', 30, 8, 8, 'passivo', 37, 'Dragonflies are a level 5 Monsters who currently inhabit territories around the Mist Village like Big Slope, By The River and Land of Water Bounty Station.', '{}'),
  ('Fire Ant', 'regular', 7, 'Big Slope, 3 Way Road Split, Bloody Pond', 45, 16, 16, 'passivo', 50, 'Fire Ants are level 7 monsters inhabiting various areas around the Mist Village, such as Big Slope, 3 Way Road Split and Bloody Pond.', '{}'),
  ('Fox', 'regular', 9, 'By The River', 65, 6, 6, 'passivo', 67, 'Foxes are a level 9 monster found in various areas around the Mist Village, mainly By The River.', '{}'),
  ('Evil Spirit', 'regular', 23, 'Sealed Temple', 150, 39, 39, 'agressivo', 172, 'The Evil Spirit in a level 23 monster located in the Sealed Temple which can be accessed after unsealing a barrier tag in the ant cave.', '{}'),
  ('Dark Weasel', 'boss', 53, 'Sand War Zone', 1, 461, 461, 'agressivo', 22000, 'The Dark Weasel is a level 53 boss monster located in the Sand War Zone map east of the Sand Village.', '{"Dark Slicing Wind - 110 damage per hit<br>","Dark Wind Scythe - 110 damage per hit<br>","Flicker"}'),
  ('Emperor Penguin', 'regular', 51, 'Iron Cave, *Iron  Forest', 800, 178, 178, 'agressivo', 390, null, '{}'),
  ('Horned Samurai', 'regular', 57, 'Iron City', 2100, 187, 187, 'agressivo', 504, null, '{"Samurai Slash"}'),
  ('Gamakura', 'boss', 62, 'Toad Mountain Lake', 72000, 300, 300, 'agressivo', 0, null, '{}'),
  ('Enraged Wild Rabbit', 'enfurecido', 1, null, 1, null, null, 'agressivo', 0, null, '{}'),
  ('Duck', 'regular', 1, 'Asoki Port, Kenko Village, Coral Walk', 10, 0, 0, 'passivo', 0, null, '{}'),
  ('Enraged Tiger', 'enfurecido', 18, 'Striped Lake, The Forest Exit', 465, 18, 18, 'agressivo', 970, 'In combat it attacks at a range of 5 and respawns every 300 seconds. It has no special jutsu.', '{}'),
  ('Enraged Wolf', 'enfurecido', 13, 'Mountain Peak, Outskirts Deadend', 330, 18, 18, 'agressivo', 670, 'In combat it attacks at a range of 10 and respawns every 300 seconds. It has no special jutsu.', '{}'),
  ('Evil Black Boar', 'regular', 1, 'Land of Water Port, Riverbend Vale', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Fat Tunneler', 'regular', 1, 'Forgotten Sands, Beach Cave', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Fierce Dragonfly', 'regular', 1, 'Windy Pond, Big Slope, Land of Water Bounty Station, Oak Trail', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Gangster Daimaru', 'boss', 28, 'Land Of Waves (Level 20 arc)', 1320, 8, 8, 'agressivo', 1458, 'In combat it attacks at a range of 10 and respawns every 300 seconds. It uses 4 jutsu in combat.', '{}'),
  ('Gangster Han', 'boss', 30, 'Land Of Waves (Level 20 arc)', 2100, 8, 8, 'agressivo', 1511, 'In combat it attacks at a range of 7 and respawns every 300 seconds. It uses 4 jutsu in combat.', '{}'),
  ('Gangster Senkoji', 'boss', 26, 'Land Of Waves (Level 20 arc)', 1100, 7, 7, 'agressivo', 1032, 'In combat it attacks at a range of 20 and respawns every 300 seconds. It uses 4 jutsu in combat.', '{}'),
  ('Hasuka', 'boss', 1, 'Level 40 story arc (see Story Lines)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Huge Scarab', 'regular', 1, 'Desert Cave Entrance, Secret Desert Cavern', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Huge White Tiger', 'regular', 1, 'Sea Breeze Vale, Path to the River Country', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Green Oni', 'regular', 1, 'Spiritstone Hollow, Land of Spirits', 1, null, null, 'agressivo', 0, 'The Green Oni is a horned oni yokai sealed inside Spiritstone Hollow.', '{}'),
  ('Guard Hayate', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Guard Hayate is one of the two guards who patrol Hyoketsu Prison, alongside Guard Yetsuo. He is killable.', '{}'),
  ('Guard Yetsuo', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Guard Yetsuo is one of the two guards who patrol Hyoketsu Prison, alongside Guard Hayate. He is killable.', '{}'),
  ('Earth Puppet', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Earth Puppet is an entry in the in-game Bestiary.', '{}'),
  ('Eddie', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Eddie is an entry in the in-game Bestiary.', '{}'),
  ('Fire Puppet', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Fire Puppet is an entry in the in-game Bestiary.', '{}'),
  ('Guardian Spirit', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Guardian Spirit is an entry in the in-game Bestiary.', '{}'),
  ('Larva', 'regular', 1, 'Leaf Village Southern Outskirts, Larva Road, Sand Nesting Ground, Slight Slope.', 18, 3, 3, 'passivo', 12, 'Larvae are a Level 1 Mob which currently inhabit the multiple areas, most notably Sand Nesting Ground west of the sand village entrance, and Larva Road south-west of the Leaf Village Gates.', '{}'),
  ('Mutant Rat', 'regular', 23, 'Leaf Village Sewers', 155, 39, 39, 'agressivo', 172, 'Mutant Rats are Level 23 monsters which currently inhabit areas of Leaf Village Sewers under the Leaf Village.', '{}'),
  ('Raccoon Bandit', 'regular', 37, 'Toad Mountain Passage', 460, 85, 85, 'passivo', 254, 'Raccoon bandits are level 37 mobs. They take places around Toad Village.', '{"Wind Barrage","Body Flicker","Leaf Genjutsu"}'),
  ('Koji', 'boss', 40, 'Chilling Corridor', 7000, 140, 140, 'agressivo', 700, 'Koji is an Aggressive Mob found at the Chilling Corridor Map west of the Chilly Canyon.', '{"Bear Traps","Body Flicker","Sensory Technique","Exploding Spiked Ball","Substitution Technique"}'),
  ('Nelinel', 'boss', 44, 'Bandit Chief''s Yard', 1, 84, 84, 'agressivo', 0, 'Nelinel is a Level 44 boss who currently inhabits the single area Bandit Chief''s Yard.', '{"Water Bullet","Colliding Wave","Stun Smash","Body Flicker"}'),
  ('Kiemon', 'boss', 43, 'Icy Pathway', 6600, 55, 55, 'agressivo', 1750, 'Kiemon is a Level 43 boss who currently inhabits the single area Southern Bandit Encampment.', '{"Great Fireball","Phoenix Fireball","Body Flicker","Combusting Vortex","Substitution Technique"}'),
  ('Kumorui', 'boss', 30, 'Cave at the bottom of Dark Clearing', 4500, 66, 66, 'agressivo', 0, 'Kumorui is BOSS-type enemy hidden inside forest like cave, you can enter in the arena only at levels 20-30.', '{"Flicker","Web Shot"}'),
  ('Old Blood Puppet', 'regular', 53, 'Blood Puppet Factory', 1500, 356, 356, 'agressivo', 0, 'An even more ancient and powerful monster than the Blood Puppet. At level 53 it''s currently the highest level enemy.', '{"Metal Chain Technique - Flicker"}'),
  ('Koitaru', 'boss', 50, 'Cursed Laboratory (Sealed Box)', 1, 325, 325, 'passivo', 0, 'Koitaru is a level 50 boss located in a sealed box at the Cursed Laboratory entrance.', '{"Bone Spikes Technique 1 (All directions)","Bone Spikes Technique 2 (Wave)"}'),
  ('Leyasu / Ieyasu', 'boss', 50, 'Final Boss Room', 14500, 210, 210, 'agressivo', 6250, 'Leyasu, also written Ieyasu, is a level 50 boss and the leader of the bandits of the Level 40 arc.', '{"Flicker","Rare ground slam","Seismic Dash","Breaking Kick"}'),
  ('Kuraken', 'regular', 60, 'South-Eastern Sea III', 150000, 762, 762, 'agressivo', 0, 'The Kuraken is a sea monster of legend which is said to inhabit the South-Eastern Sea III map.', '{"Body Flicker","Bone Spikes"}'),
  ('Nobu', 'boss', 59, 'Iron Tower', 41000, 589, 589, 'agressivo', 0, 'General Nobu is a level 59 boss located in the Iron Tower area, in the most northern part of the Land Of Iron.', '{"Flicker","Dark Whirling Technique","Crescent Moon Behading"}'),
  ('Leno', 'boss', 32, 'Fallen Stones Gorge', 3500, 73, 73, 'agressivo', 2200, null, '{}'),
  ('King Bear', 'regular', 1, 'Forest Near the Ledge', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Lenno', 'boss', 1, 'Fallen Stone Gorge (ID 120)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Mad Desert Coyote', 'enfurecido', 1, 'Desert Oasis, West Desert Valley, Howling Canyon II', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Mother Scarab', 'regular', 1, 'Desert Cave Entrance (ID 39)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Overgrown Stinger', 'regular', 1, 'Sand Hive Grounds, Howling Canyon', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Prison Guards', 'regular', 1, 'Hyoketsu Prison (ID 19)', 1, null, null, 'passivo', 0, null, '{}'),
  ('Rabid Wolf', 'regular', 1, 'River Outskirts (ID 123)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Raging Boar', 'regular', 1, 'Verdant Edge II, Misty Hides', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Kappa', 'regular', 65, 'Land of Spirits', 1500, 19, 19, 'agressivo', 480, 'The Kappa is a hostile yokai found in the Land of Spirits, twisted by the dark influence spreading through the spirit realm.', '{}'),
  ('Karakasa', 'regular', 1, 'Spiritwind Ascent, Land of Spirits', 1, null, null, 'agressivo', 0, 'The Karakasa is a hostile umbrella yokai found around Spiritwind Ascent in the Land of Spirits.', '{}'),
  ('Ongaku', 'boss', 71, 'Land of Spirits', 21510, 42, 42, 'agressivo', 8866, 'Ongaku is a Level 71 boss yokai. With 21,510 health, a 10 minute respawn, and a long 18 tile range, she is one of the toughest fights in the region.', '{}'),
  ('Kikkumaru', 'boss', 74, 'Land of Spirits', 24150, 48, 48, 'agressivo', 9250, 'Kikkumaru is a Level 74 boss yokai of the Land of Spirits with 24,150 health and a 10 minute respawn.', '{}'),
  ('Jirou', 'boss', 72, 'Land of Spirits', 26292, 44, 44, 'agressivo', 9000, 'Jirou is a Level 72 boss yokai of the Land of Spirits with 26,292 health and a 10 minute respawn.', '{}'),
  ('Purple Oni', 'regular', 1, 'Spiritstone Hollow, Land of Spirits', 1, null, null, 'agressivo', 0, 'The Purple Oni is a horned oni yokai sealed inside Spiritstone Hollow.', '{}'),
  ('Mother Crystal Slug', 'regular', 42, 'Not yet documented', 4200, 20, 20, 'agressivo', 2500, 'The Mother Crystal Slug is a level 42 mob and the larger counterpart to the Crystal Slug.', '{}'),
  ('Karoshi', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Karoshi is an entry in the in-game Bestiary.', '{}'),
  ('Mad Emperor Penguin', 'enfurecido', 1, null, 1, null, null, 'agressivo', 0, 'Mad Emperor Penguin is an entry in the in-game Bestiary.', '{}'),
  ('Mother Slug', 'boss', 1, null, 1, null, null, 'agressivo', 0, 'Mother Slug is an entry in the in-game Bestiary.', '{}'),
  ('Nina', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Nina is an entry in the in-game Bestiary.', '{}'),
  ('Ninken', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Ninken is an entry in the in-game Bestiary.', '{}'),
  ('Panda King', 'boss', 1, null, 1, null, null, 'agressivo', 0, 'Panda King is an entry in the in-game Bestiary.', '{}'),
  ('Poison Puppet', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Poison Puppet is an entry in the in-game Bestiary.', '{}'),
  ('Scorpion', 'regular', 5, 'Desert Plains', 30, 10, 10, 'passivo', 37, 'Scorpions are Level 5 Mob which currently inhabit a few maps around the Sand Village.', '{}'),
  ('Spiderling', 'regular', 5, 'Moist Plains, Near the Valley', 30, 10, 10, 'passivo', 37, 'Spiderlings are Level 5 monsters which currently inhabit various locations around the Leaf Village, most notably Moist Plains and Near the Valley.', '{}'),
  ('Snakes', 'regular', 30, 'Hidden Lair', 215, 90, 90, 'agressivo', 250, 'Snakes are Level 30 monsters which currently inhabit Hidden Lair Entrance map.', '{}'),
  ('Venomous Snake', 'regular', 32, 'Hidden Lair', 230, 64, 64, 'agressivo', 255, 'Venomous Snakes are Level 32 monsters that currently inhabit the Hidden Lair map.', '{}'),
  ('Stinger', 'regular', 7, 'Sand Hive Grounds', 45, 16, 16, 'passivo', 50, 'Stingers are Level 7 monsters which currently inhabit the various maps around the Sand Village, most noticeably Sand Hive Grounds.', '{}'),
  ('Tunneler', 'regular', 17, 'Desert Oasis', 116, 44, 44, 'agressivo', 127, 'Tunnelers are a Level 17 Mob which currently inhabit Desert Oasis (west of the Sand Village) and Infested Desert Road.', '{}'),
  ('Scarab', 'regular', 13, 'Desert Cave Entrance', 85, 26, 26, 'agressivo', 97, 'Scarab are Level 13 monsters which currently inhabit one location, named the Desert Cave Entrance.', '{}'),
  ('Tiger', 'regular', 13, 'Striped Lake, The Forest Exit, , Path to the River Country', 85, 26, 26, 'agressivo', 97, 'Tigers are a Level 13 monsters which currently inhabit various locations around the Leaf Village, most notably East of Katabami Bridge.', '{}'),
  ('Tause', 'boss', 40, 'Southern Bandit Encampment', 2100, 62, 62, 'agressivo', 900, 'Tause are Level 40 Mob which currently inhabit the single area. Southern Bandit Encampment with his partner Takeshi at North of Icy Pathway.', '{"Body Flicker","Wild Slashes"}'),
  ('Takeshi', 'boss', 41, 'Southern Bandit Encampment', 1700, 128, 128, 'agressivo', 0, 'Takeshi is Level 41 boss who currently inhabits the single area Southern Bandit Encampment with his partner Tause North of Icy Pathway.', '{"Body Flicker","Fuuma Shuriken"}'),
  ('Reain', 'boss', 45, 'Bandit''s House', 3040, 92, 92, 'agressivo', 2200, 'Reain is a Level 45 boss who currently inhabits the single area Lake Stasis. She is here with her partner Chei and 5 Alpha Wolf.', '{"Wind Barrage","Slashing Tornado","Triple Slashing Tornadoes","Body Flicker","Substitution Technique"}'),
  ('Rat Kage', 'boss', 33, 'Leaf Village Sewers (F2)', 1550, 352, 352, 'passivo', 2050, null, '{"Lightning Senbon Technique","Lightning Spear Technique","Lighting Current Technique"}'),
  ('Tanuki', 'boss', 29, 'Bamboo Forest', 350, 67, 67, 'passivo', 0, 'Tanuki is a level 29 mini-boss type monster located in the Mist Bamboo Forest north of the Misty Hides.', '{"Leaf Genjutsu (stun)"}'),
  ('Samurai', 'regular', 56, 'Iron City', 1200, 227, 227, 'agressivo', 446, null, '{"Shockwave Slash","Body Flicker"}'),
  ('Romaji', 'boss', 50, 'Hunter''s Marsh', 23000, 306, 306, 'agressivo', 12500, null, '{"Dark Whirlwind Kick","Hunter Warglaive Boomerang","Hunter Warglaive Attack","Body Flicker","Subsitution Jutsu"}'),
  ('Reian', 'boss', 1, 'Level 40 story arc (see Story Lines)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Shizu', 'boss', 19, 'Kinsen Quarters (ID 18)', 1000, 10, 10, 'agressivo', 1183, 'In combat it attacks at a range of 8 and respawns every 300 seconds. It uses 5 jutsu in combat.', '{}'),
  ('Silk Moth', 'regular', 45, 'River Outskirts (ID 123)', 660, 16, 16, 'agressivo', 337, 'In combat it attacks at a range of 15 and respawns every 80 seconds. It uses 1 jutsu in combat.', '{}'),
  ('Spicy Venomous Snake', 'regular', 1, 'Abandoned Lair Entrance (ID 62)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Spirit Fox', 'regular', 1, 'By the River, Oak Trail', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Tsuchigumo', 'regular', 64, 'Land of Spirits', 1400, 18, 18, 'agressivo', 472, 'The Tsuchigumo is a hostile yokai found in the Land of Spirits, twisted by the dark influence spreading through the spirit realm.', '{}'),
  ('Tengu Guard', 'regular', 68, 'Land of Spirits', 1800, 21, 21, 'agressivo', 510, 'The Tengu Guard is a hostile Level 68 tengu yokai found in the Land of Spirits.', '{}'),
  ('Red Oni', 'regular', 70, 'Land of Spirits', 8500, 35, 35, 'agressivo', 4375, 'The Red Oni is a hostile Level 70 oni yokai found in the Land of Spirits. With 8,500 health, heavy damage, and a 5 minute respawn, it is the elite of the oni family.', '{}'),
  ('Red Betobeto', 'regular', 1, 'Spiritevil Falls, Land of Spirits', 1, null, null, 'agressivo', 0, 'The Red Betobeto is a hostile yokai found at Spiritevil Falls in the Land of Spirits.', '{}'),
  ('White Betobeto', 'regular', 1, 'Spiritevil Falls, Land of Spirits', 1, null, null, 'agressivo', 0, 'The White Betobeto is a hostile yokai found at Spiritevil Falls in the Land of Spirits.', '{}'),
  ('Shinkai Crab', 'boss', 56, 'Beach Cave (War Zone)', 16000, 25, 25, 'agressivo', 5000, 'The Shinkai Crab is an open world boss added on July 25, 2026.', '{"Seis ataques (temas de água","gelo e terra)"}'),
  ('Reyha', 'boss', 45, 'Desert (exact map not yet confirmed)', 10000, 25, 25, 'agressivo', 5000, 'Reyha is an open world boss added on August 9, 2026. She is a former Sand ninja who abandoned her village and now lives alone in the desert.', '{"Fights with a boomerang. Roaming NPC type since 18 August 2026"}'),
  ('Royal Spirit', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Royal Spirit is an entry in the in-game Bestiary.', '{}'),
  ('Scythe Weasel', 'boss', 1, null, 1, null, null, 'agressivo', 0, 'Scythe Weasel is an entry in the in-game Bestiary.', '{}'),
  ('Torii', 'boss', 1, null, 1, null, null, 'agressivo', 0, 'Torii is an entry in the in-game Bestiary.', '{}'),
  ('Trash Bag', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Trash Bag is an entry in the in-game Bestiary.', '{}'),
  ('War Toad', 'boss', 1, null, 1, null, null, 'agressivo', 0, 'War Toad is an entry in the in-game Bestiary.', '{}'),
  ('Weird Frog', 'regular', 1, null, 1, null, null, 'agressivo', 0, 'Weird Frog is an entry in the in-game Bestiary.', '{}'),
  ('Spooky Crow', 'regular', 1, null, 1, null, null, 'agressivo', 0, null, '{}'),
  ('Spooky Bat', 'regular', 1, null, 1, null, null, 'agressivo', 0, null, '{}'),
  ('Wolf', 'regular', 9, 'Outskirts Dead End', 60, 18, 18, 'passivo', 67, 'Wolves are Level 9 monsters which currently inhabit areas near the leaf village, most notably Outskirts Dead End.', '{}'),
  ('White Tiger', 'regular', 17, 'Striped Lake, The Forest Exit, Path to the River Country', 120, 44, 44, 'agressivo', 127, 'White Tigers are a Level 17 Mob which currently inhabit various locations around the Leaf Village, most notably on the south of the village.', '{}'),
  ('Wild Rabbit', 'regular', 3, 'Oak Trail', 1, null, null, 'passivo', 0, null, '{}'),
  ('Yuno', 'boss', 1, 'Mysterious Well (inside Crystallflow Falls, ID 26)', 1, null, null, 'agressivo', 0, null, '{}'),
  ('Yellow Oni', 'regular', 1, 'Spiritstone Hollow, Land of Spirits', 1, null, null, 'agressivo', 0, 'The Yellow Oni is a horned oni yokai sealed inside Spiritstone Hollow.', '{}')
on conflict (lower(name)) do update set
  category = excluded.category,
  level = excluded.level,
  location_note = excluded.location_note,
  hp = excluded.hp,
  damage_min = excluded.damage_min,
  damage_max = excluded.damage_max,
  combat_type = excluded.combat_type,
  xp_reward = excluded.xp_reward,
  description = excluded.description,
  special_abilities = excluded.special_abilities;

-- ---------------------------------------------------------------
-- Drops (mobs <-> itens)
-- ---------------------------------------------------------------
insert into mob_drops (mob_id, item_id, drop_rate) values
  ((select id from mobs where lower(name) = lower('Big Scarabs')), (select id from items where lower(name) = lower('Big Scarab Shell')), null),
  ((select id from mobs where lower(name) = lower('Big Scarabs')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Big Scarabs')), (select id from items where lower(name) = lower('Seji no Hani')), null),
  ((select id from mobs where lower(name) = lower('Bear')), (select id from items where lower(name) = lower('Bear Paw')), 10.0),
  ((select id from mobs where lower(name) = lower('Bear')), (select id from items where lower(name) = lower('Blank Scroll')), 1.0),
  ((select id from mobs where lower(name) = lower('Alpha Wolf')), (select id from items where lower(name) = lower('Wolf Fur')), 20.0),
  ((select id from mobs where lower(name) = lower('Alpha Wolf')), (select id from items where lower(name) = lower('Blank Scroll')), 5.0),
  ((select id from mobs where lower(name) = lower('Alpha Wolf')), (select id from items where lower(name) = lower('Prowler Pants')), 1.0),
  ((select id from mobs where lower(name) = lower('Alpha Wolf')), (select id from items where lower(name) = lower('Tanned Leather')), 5.0),
  ((select id from mobs where lower(name) = lower('Cursed Host')), (select id from items where lower(name) = lower('DNA Sample')), null),
  ((select id from mobs where lower(name) = lower('Cursed Host')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Cursed Host')), (select id from items where lower(name) = lower('Religious Katana')), null),
  ((select id from mobs where lower(name) = lower('Cursed Host')), (select id from items where lower(name) = lower('Iron Scythe')), null),
  ((select id from mobs where lower(name) = lower('Bee')), (select id from items where lower(name) = lower('Honey Comb')), null),
  ((select id from mobs where lower(name) = lower('Bee')), (select id from items where lower(name) = lower('Insect Wing')), null),
  ((select id from mobs where lower(name) = lower('Bee')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Bee Hive')), (select id from items where lower(name) = lower('Honey comb')), null),
  ((select id from mobs where lower(name) = lower('Chei')), (select id from items where lower(name) = lower('Black Masked Top')), 1.0),
  ((select id from mobs where lower(name) = lower('Chei')), (select id from items where lower(name) = lower('Black Bandit Shoes')), 1.0),
  ((select id from mobs where lower(name) = lower('Chei')), (select id from items where lower(name) = lower('Black Bandit Pants')), 1.0),
  ((select id from mobs where lower(name) = lower('Chei')), (select id from items where lower(name) = lower('Tonfa')), 1.0),
  ((select id from mobs where lower(name) = lower('Chei')), (select id from items where lower(name) = lower('Blood Vial')), 50.0),
  ((select id from mobs where lower(name) = lower('Blood Puppet')), (select id from items where lower(name) = lower('Puppet head')), null),
  ((select id from mobs where lower(name) = lower('Blood Puppet')), (select id from items where lower(name) = lower('Puppet limb')), null),
  ((select id from mobs where lower(name) = lower('Blood Puppet')), (select id from items where lower(name) = lower('Puppet string')), null),
  ((select id from mobs where lower(name) = lower('Blood Puppet')), (select id from items where lower(name) = lower('Blood Engine')), null),
  ((select id from mobs where lower(name) = lower('Ant')), (select id from items where lower(name) = lower('Ant Feelers')), null),
  ((select id from mobs where lower(name) = lower('Ant')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Boar')), (select id from items where lower(name) = lower('Boar Tusk')), null),
  ((select id from mobs where lower(name) = lower('Boar')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Black Boar')), (select id from items where lower(name) = lower('Boar Tusk')), null),
  ((select id from mobs where lower(name) = lower('Black Boar')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Black Boar')), (select id from items where lower(name) = lower('Dark Fur')), null),
  ((select id from mobs where lower(name) = lower('Dark Monkey King')), (select id from items where lower(name) = lower('Adamantine Staff')), null),
  ((select id from mobs where lower(name) = lower('Dark Monkey King')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Admiral Mitsuhide')), (select id from items where lower(name) = lower('Yamazaru')), null),
  ((select id from mobs where lower(name) = lower('Admiral Mitsuhide')), (select id from items where lower(name) = lower('Jakuma')), null),
  ((select id from mobs where lower(name) = lower('Bear Hermit')), (select id from items where lower(name) = lower('Black Bear Hood')), null),
  ((select id from mobs where lower(name) = lower('Bear Hermit')), (select id from items where lower(name) = lower('Black Arm Bandages')), null),
  ((select id from mobs where lower(name) = lower('Bear Hermit')), (select id from items where lower(name) = lower('Reinforced Bo Staff')), null),
  ((select id from mobs where lower(name) = lower('Bear Hermit')), (select id from items where lower(name) = lower('Raging Hermit Pants')), null),
  ((select id from mobs where lower(name) = lower('Bat')), (select id from items where lower(name) = lower('Bat Wings')), null),
  ((select id from mobs where lower(name) = lower('Bat')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Bat')), (select id from items where lower(name) = lower('Vigilante Bandana Mask Recipe')), null),
  ((select id from mobs where lower(name) = lower('Bat')), (select id from items where lower(name) = lower('Hokuto Sphere II')), null),
  ((select id from mobs where lower(name) = lower('Crystal Slug')), (select id from items where lower(name) = lower('Crystal Pipe')), null),
  ((select id from mobs where lower(name) = lower('Daimaru')), (select id from items where lower(name) = lower('Wooden Tonfa')), null),
  ((select id from mobs where lower(name) = lower('Captain Midora')), (select id from items where lower(name) = lower('Sukarabe Omo')), null),
  ((select id from mobs where lower(name) = lower('Captain Midora')), (select id from items where lower(name) = lower('Winter Scarf')), null),
  ((select id from mobs where lower(name) = lower('Captain Midora')), (select id from items where lower(name) = lower('Crystal Fan')), null),
  ((select id from mobs where lower(name) = lower('Captain Midora')), (select id from items where lower(name) = lower('Hokuto Sphere IV')), null),
  ((select id from mobs where lower(name) = lower('Captain Midora')), (select id from items where lower(name) = lower('Iron Piece')), null),
  ((select id from mobs where lower(name) = lower('Captain Midora')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Blight Leech')), (select id from items where lower(name) = lower('Black Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Blight Leech')), (select id from items where lower(name) = lower('Hokuto Sphere I')), null),
  ((select id from mobs where lower(name) = lower('Blight Leech')), (select id from items where lower(name) = lower('Leech Fang')), null),
  ((select id from mobs where lower(name) = lower('Blight Leech')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Blight Leech')), (select id from items where lower(name) = lower('Leech Shell')), null),
  ((select id from mobs where lower(name) = lower('Blight Leech')), (select id from items where lower(name) = lower('Black Backpack')), null),
  ((select id from mobs where lower(name) = lower('Crimson Leech')), (select id from items where lower(name) = lower('Red Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Crimson Leech')), (select id from items where lower(name) = lower('Hokuto Sphere II')), null),
  ((select id from mobs where lower(name) = lower('Crimson Leech')), (select id from items where lower(name) = lower('Leech Fang')), null),
  ((select id from mobs where lower(name) = lower('Crimson Leech')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Crimson Leech')), (select id from items where lower(name) = lower('Leech Shell')), null),
  ((select id from mobs where lower(name) = lower('Crimson Leech')), (select id from items where lower(name) = lower('Red Backpack')), null),
  ((select id from mobs where lower(name) = lower('Angry Hawk')), (select id from items where lower(name) = lower('Hawk Talon')), null),
  ((select id from mobs where lower(name) = lower('Angry Hawk')), (select id from items where lower(name) = lower('Hawk Feather')), null),
  ((select id from mobs where lower(name) = lower('Angry Hawk')), (select id from items where lower(name) = lower('Egg')), null),
  ((select id from mobs where lower(name) = lower('Angry Hawk')), (select id from items where lower(name) = lower('Tengai Hat')), null),
  ((select id from mobs where lower(name) = lower('Bad Raccoon Bandit')), (select id from items where lower(name) = lower('Raccoon Tail')), null),
  ((select id from mobs where lower(name) = lower('Bad Raccoon Bandit')), (select id from items where lower(name) = lower('Tanned Leather')), null),
  ((select id from mobs where lower(name) = lower('Big Scorpion')), (select id from items where lower(name) = lower('Scorpion Tail')), null),
  ((select id from mobs where lower(name) = lower('Black Bear')), (select id from items where lower(name) = lower('Black Bear Paws')), null),
  ((select id from mobs where lower(name) = lower('Black Bear')), (select id from items where lower(name) = lower('Tanned Leather')), null),
  ((select id from mobs where lower(name) = lower('Black Bear')), (select id from items where lower(name) = lower('Dark Barbarian Cloak Recipe')), null),
  ((select id from mobs where lower(name) = lower('Crab')), (select id from items where lower(name) = lower('Red Fighter Pants')), null),
  ((select id from mobs where lower(name) = lower('Crab')), (select id from items where lower(name) = lower('Red Striped Bucket Hat')), null),
  ((select id from mobs where lower(name) = lower('Crazy Spider')), (select id from items where lower(name) = lower('Spider Eggs')), null),
  ((select id from mobs where lower(name) = lower('Crazy Spider')), (select id from items where lower(name) = lower('Silk')), null),
  ((select id from mobs where lower(name) = lower('Desert Coyote')), (select id from items where lower(name) = lower('Canine Fang')), null),
  ((select id from mobs where lower(name) = lower('Desert Coyote')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Desert Coyote')), (select id from items where lower(name) = lower('Blue Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Guren')), (select id from items where lower(name) = lower('Blank Scroll')), 1.0),
  ((select id from mobs where lower(name) = lower('Gafuki')), (select id from items where lower(name) = lower('Great Grandfather''s Muramasa')), 5.0),
  ((select id from mobs where lower(name) = lower('Gafuki')), (select id from items where lower(name) = lower('Black Giant Folding Fan')), 5.0),
  ((select id from mobs where lower(name) = lower('Gafuki')), (select id from items where lower(name) = lower('Blank Scroll')), 5.0),
  ((select id from mobs where lower(name) = lower('Glacier Bear')), (select id from items where lower(name) = lower('Gray Bear Paw')), null),
  ((select id from mobs where lower(name) = lower('Glacier Bear')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Hawk')), (select id from items where lower(name) = lower('Hawk Talon')), null),
  ((select id from mobs where lower(name) = lower('Hawk')), (select id from items where lower(name) = lower('Hawk Feather')), null),
  ((select id from mobs where lower(name) = lower('Hawk')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Hornet')), (select id from items where lower(name) = lower('Honey Comb')), null),
  ((select id from mobs where lower(name) = lower('Hornet')), (select id from items where lower(name) = lower('Insect Wings')), null),
  ((select id from mobs where lower(name) = lower('Hornet')), (select id from items where lower(name) = lower('Blank Scroll.')), null),
  ((select id from mobs where lower(name) = lower('Hebimaru')), (select id from items where lower(name) = lower('Shirokata')), null),
  ((select id from mobs where lower(name) = lower('Hebimaru')), (select id from items where lower(name) = lower('Snake Rope Belt')), null),
  ((select id from mobs where lower(name) = lower('Hebimaru')), (select id from items where lower(name) = lower('Snake Inner Kimono')), null),
  ((select id from mobs where lower(name) = lower('Dragonfly')), (select id from items where lower(name) = lower('Dragonfly wings')), null),
  ((select id from mobs where lower(name) = lower('Dragonfly')), (select id from items where lower(name) = lower('Blank scroll')), null),
  ((select id from mobs where lower(name) = lower('Fire Ant')), (select id from items where lower(name) = lower('Ant Feelers')), null),
  ((select id from mobs where lower(name) = lower('Fire Ant')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Fox')), (select id from items where lower(name) = lower('Fox Fur')), null),
  ((select id from mobs where lower(name) = lower('Fox')), (select id from items where lower(name) = lower('Blank Scrolls')), null),
  ((select id from mobs where lower(name) = lower('Fox')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('Evil Spirit')), (select id from items where lower(name) = lower('Undead Charm')), null),
  ((select id from mobs where lower(name) = lower('Evil Spirit')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Evil Spirit')), (select id from items where lower(name) = lower('Seathorn Pipe')), null),
  ((select id from mobs where lower(name) = lower('Dark Weasel')), (select id from items where lower(name) = lower('Dark Scythes')), null),
  ((select id from mobs where lower(name) = lower('Dark Weasel')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Emperor Penguin')), (select id from items where lower(name) = lower('Penguin Beak')), null),
  ((select id from mobs where lower(name) = lower('Emperor Penguin')), (select id from items where lower(name) = lower('Crystal Fan')), null),
  ((select id from mobs where lower(name) = lower('Emperor Penguin')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Horned Samurai')), (select id from items where lower(name) = lower('Iron Piece')), null),
  ((select id from mobs where lower(name) = lower('Horned Samurai')), (select id from items where lower(name) = lower('Iron Prison Key')), null),
  ((select id from mobs where lower(name) = lower('Horned Samurai')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Gamakura')), (select id from items where lower(name) = lower('Mizukane?')), null),
  ((select id from mobs where lower(name) = lower('Duck')), (select id from items where lower(name) = lower('Eggs')), null),
  ((select id from mobs where lower(name) = lower('Duck')), (select id from items where lower(name) = lower('Green Striped Bucket Hat')), null),
  ((select id from mobs where lower(name) = lower('Enraged Tiger')), (select id from items where lower(name) = lower('Tanned Leather')), null),
  ((select id from mobs where lower(name) = lower('Enraged Tiger')), (select id from items where lower(name) = lower('Straw Hat')), null),
  ((select id from mobs where lower(name) = lower('Enraged Wolf')), (select id from items where lower(name) = lower('Tanned Leather')), null),
  ((select id from mobs where lower(name) = lower('Evil Black Boar')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('Evil Black Boar')), (select id from items where lower(name) = lower('Hanging Sakkat')), null),
  ((select id from mobs where lower(name) = lower('Fat Tunneler')), (select id from items where lower(name) = lower('White Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Fierce Dragonfly')), (select id from items where lower(name) = lower('Dragonfly Wings')), null),
  ((select id from mobs where lower(name) = lower('Fierce Dragonfly')), (select id from items where lower(name) = lower('Whiter Fighter Pants')), null),
  ((select id from mobs where lower(name) = lower('Fierce Dragonfly')), (select id from items where lower(name) = lower('Red Twinfall Scarf Recipe')), null),
  ((select id from mobs where lower(name) = lower('Gangster Daimaru')), (select id from items where lower(name) = lower('Finger')), null),
  ((select id from mobs where lower(name) = lower('Gangster Daimaru')), (select id from items where lower(name) = lower('Tengu Mask')), null),
  ((select id from mobs where lower(name) = lower('Gangster Han')), (select id from items where lower(name) = lower('Finger')), null),
  ((select id from mobs where lower(name) = lower('Gangster Han')), (select id from items where lower(name) = lower('Old Tengu Mask')), null),
  ((select id from mobs where lower(name) = lower('Gangster Senkoji')), (select id from items where lower(name) = lower('Finger')), null),
  ((select id from mobs where lower(name) = lower('Gangster Senkoji')), (select id from items where lower(name) = lower('Beaded Necklace')), null),
  ((select id from mobs where lower(name) = lower('Huge Scarab')), (select id from items where lower(name) = lower('Big Scarab Shells')), null),
  ((select id from mobs where lower(name) = lower('Huge Scarab')), (select id from items where lower(name) = lower('Green Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Huge Scarab')), (select id from items where lower(name) = lower('Seji No Hani')), null),
  ((select id from mobs where lower(name) = lower('Huge Scarab')), (select id from items where lower(name) = lower('Large Scarab Pincers')), null),
  ((select id from mobs where lower(name) = lower('Huge White Tiger')), (select id from items where lower(name) = lower('Tanned Leather')), null),
  ((select id from mobs where lower(name) = lower('Huge White Tiger')), (select id from items where lower(name) = lower('White Straw Hat')), null),
  ((select id from mobs where lower(name) = lower('Huge White Tiger')), (select id from items where lower(name) = lower('White Fighter Pants')), null),
  ((select id from mobs where lower(name) = lower('Larva')), (select id from items where lower(name) = lower('Cocoon')), null),
  ((select id from mobs where lower(name) = lower('Larva')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Mutant Rat')), (select id from items where lower(name) = lower('Rat Tail')), null),
  ((select id from mobs where lower(name) = lower('Mutant Rat')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Mutant Rat')), (select id from items where lower(name) = lower('Twin Fangs')), null),
  ((select id from mobs where lower(name) = lower('Raccoon Bandit')), (select id from items where lower(name) = lower('Raccoon Tail')), null),
  ((select id from mobs where lower(name) = lower('Raccoon Bandit')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Raccoon Bandit')), (select id from items where lower(name) = lower('Tales of a Gutsy Ninja')), null),
  ((select id from mobs where lower(name) = lower('Koji')), (select id from items where lower(name) = lower('White Bandit Mask')), 1.0),
  ((select id from mobs where lower(name) = lower('Koji')), (select id from items where lower(name) = lower('Black Bandit Mask')), 1.0),
  ((select id from mobs where lower(name) = lower('Nelinel')), (select id from items where lower(name) = lower('Red Scarf')), null),
  ((select id from mobs where lower(name) = lower('Nelinel')), (select id from items where lower(name) = lower('Double Arm Bandages')), null),
  ((select id from mobs where lower(name) = lower('Kiemon')), (select id from items where lower(name) = lower('Sashed Baggy Pants')), 1.0),
  ((select id from mobs where lower(name) = lower('Kiemon')), (select id from items where lower(name) = lower('Blood Vial')), 50.0),
  ((select id from mobs where lower(name) = lower('Kumorui')), (select id from items where lower(name) = lower('Leg Bandage')), null),
  ((select id from mobs where lower(name) = lower('Kumorui')), (select id from items where lower(name) = lower('Arm Bandage')), null),
  ((select id from mobs where lower(name) = lower('Kumorui')), (select id from items where lower(name) = lower('Chest Bandages')), null),
  ((select id from mobs where lower(name) = lower('Old Blood Puppet')), (select id from items where lower(name) = lower('Blood Engine')), null),
  ((select id from mobs where lower(name) = lower('Old Blood Puppet')), (select id from items where lower(name) = lower('Puppet string')), null),
  ((select id from mobs where lower(name) = lower('Old Blood Puppet')), (select id from items where lower(name) = lower('Puppet head')), null),
  ((select id from mobs where lower(name) = lower('Old Blood Puppet')), (select id from items where lower(name) = lower('Puppet limb')), null),
  ((select id from mobs where lower(name) = lower('Koitaru')), (select id from items where lower(name) = lower('Snake Belt')), null),
  ((select id from mobs where lower(name) = lower('Koitaru')), (select id from items where lower(name) = lower('Kotsuzui Tanto')), null),
  ((select id from mobs where lower(name) = lower('Koitaru')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Koitaru')), (select id from items where lower(name) = lower('Snake Inner Kimono')), null),
  ((select id from mobs where lower(name) = lower('Leyasu / Ieyasu')), (select id from items where lower(name) = lower('Demon Claws')), 1.0),
  ((select id from mobs where lower(name) = lower('Leyasu / Ieyasu')), (select id from items where lower(name) = lower('Blood Vial')), 50.0),
  ((select id from mobs where lower(name) = lower('Kuraken')), (select id from items where lower(name) = lower('Asarihanma')), null),
  ((select id from mobs where lower(name) = lower('Nobu')), (select id from items where lower(name) = lower('Blood Iron Fan')), null),
  ((select id from mobs where lower(name) = lower('Nobu')), (select id from items where lower(name) = lower('Adamantine Sword')), null),
  ((select id from mobs where lower(name) = lower('Leno')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Leno')), (select id from items where lower(name) = lower('Hohuto Sphere II')), null),
  ((select id from mobs where lower(name) = lower('Leno')), (select id from items where lower(name) = lower('Raging Hermit Shirt')), null),
  ((select id from mobs where lower(name) = lower('Leno')), (select id from items where lower(name) = lower('Canine Fang')), null),
  ((select id from mobs where lower(name) = lower('King Bear')), (select id from items where lower(name) = lower('Brownbear Paws')), null),
  ((select id from mobs where lower(name) = lower('King Bear')), (select id from items where lower(name) = lower('Tanned Leather')), null),
  ((select id from mobs where lower(name) = lower('Mad Desert Coyote')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('Mad Desert Coyote')), (select id from items where lower(name) = lower('Blue Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Mother Scarab')), (select id from items where lower(name) = lower('Scarab Shell')), null),
  ((select id from mobs where lower(name) = lower('Overgrown Stinger')), (select id from items where lower(name) = lower('Scorpion Tail')), null),
  ((select id from mobs where lower(name) = lower('Rabid Wolf')), (select id from items where lower(name) = lower('Rabid Hide')), null),
  ((select id from mobs where lower(name) = lower('Rabid Wolf')), (select id from items where lower(name) = lower('Teeth')), null),
  ((select id from mobs where lower(name) = lower('Raging Boar')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('Mother Crystal Slug')), (select id from items where lower(name) = lower('Blue Masked Top')), null),
  ((select id from mobs where lower(name) = lower('Mother Crystal Slug')), (select id from items where lower(name) = lower('Blue Bandit Mask')), null),
  ((select id from mobs where lower(name) = lower('Scorpion')), (select id from items where lower(name) = lower('Scorpion Tail')), null),
  ((select id from mobs where lower(name) = lower('Scorpion')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Spiderling')), (select id from items where lower(name) = lower('Spider Eggs')), null),
  ((select id from mobs where lower(name) = lower('Spiderling')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Snakes')), (select id from items where lower(name) = lower('Snake Venom')), null),
  ((select id from mobs where lower(name) = lower('Snakes')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Venomous Snake')), (select id from items where lower(name) = lower('Snake Venom')), null),
  ((select id from mobs where lower(name) = lower('Venomous Snake')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Stinger')), (select id from items where lower(name) = lower('Scorpion Tail')), null),
  ((select id from mobs where lower(name) = lower('Stinger')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Tunneler')), (select id from items where lower(name) = lower('Tunneler Tongue')), null),
  ((select id from mobs where lower(name) = lower('Tunneler')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Scarab')), (select id from items where lower(name) = lower('Scarab Shell')), null),
  ((select id from mobs where lower(name) = lower('Scarab')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Tiger')), (select id from items where lower(name) = lower('Tiger Fur')), null),
  ((select id from mobs where lower(name) = lower('Tiger')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Tiger')), (select id from items where lower(name) = lower('Straw Hat')), null),
  ((select id from mobs where lower(name) = lower('Tiger')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('Tause')), (select id from items where lower(name) = lower('Black Bandit Blade')), 1.0),
  ((select id from mobs where lower(name) = lower('Tause')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Tause')), (select id from items where lower(name) = lower('Gas Mask')), 5.0),
  ((select id from mobs where lower(name) = lower('Tause')), (select id from items where lower(name) = lower('Blood Vial')), 50.0),
  ((select id from mobs where lower(name) = lower('Takeshi')), (select id from items where lower(name) = lower('Blood Vial')), null),
  ((select id from mobs where lower(name) = lower('Takeshi')), (select id from items where lower(name) = lower('Raging Bandit Pants')), null),
  ((select id from mobs where lower(name) = lower('Reain')), (select id from items where lower(name) = lower('Oriental Fan')), 1.0),
  ((select id from mobs where lower(name) = lower('Reain')), (select id from items where lower(name) = lower('Gloves Knuckle')), 1.0),
  ((select id from mobs where lower(name) = lower('Reain')), (select id from items where lower(name) = lower('Nitoryu Recipe')), 5.0),
  ((select id from mobs where lower(name) = lower('Reain')), (select id from items where lower(name) = lower('Blood Vial')), 50.0),
  ((select id from mobs where lower(name) = lower('Rat Kage')), (select id from items where lower(name) = lower('Rat Tail')), null),
  ((select id from mobs where lower(name) = lower('Rat Kage')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Rat Kage')), (select id from items where lower(name) = lower('Twin Blades')), null),
  ((select id from mobs where lower(name) = lower('Tanuki')), (select id from items where lower(name) = lower('Bamboo Hat')), null),
  ((select id from mobs where lower(name) = lower('Tanuki')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Samurai')), (select id from items where lower(name) = lower('Iron Piece')), null),
  ((select id from mobs where lower(name) = lower('Samurai')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Romaji')), (select id from items where lower(name) = lower('Hunters Warglaive')), 5.0),
  ((select id from mobs where lower(name) = lower('Romaji')), (select id from items where lower(name) = lower('Romaji Bandit Pants')), 20.0),
  ((select id from mobs where lower(name) = lower('Romaji')), (select id from items where lower(name) = lower('Hokutso Sphere III')), 5.0),
  ((select id from mobs where lower(name) = lower('Romaji')), (select id from items where lower(name) = lower('Blank Scroll')), 50.0),
  ((select id from mobs where lower(name) = lower('Romaji')), (select id from items where lower(name) = lower('Random Tools Pack')), 5.0),
  ((select id from mobs where lower(name) = lower('Romaji')), (select id from items where lower(name) = lower('Dark Veiled Sakkat Recipe')), 1.0),
  ((select id from mobs where lower(name) = lower('Shizu')), (select id from items where lower(name) = lower('Mobster Ring')), null),
  ((select id from mobs where lower(name) = lower('Silk Moth')), (select id from items where lower(name) = lower('Silk')), null),
  ((select id from mobs where lower(name) = lower('Silk Moth')), (select id from items where lower(name) = lower('Moth Wings')), null),
  ((select id from mobs where lower(name) = lower('Spicy Venomous Snake')), (select id from items where lower(name) = lower('Venom')), null),
  ((select id from mobs where lower(name) = lower('Spicy Venomous Snake')), (select id from items where lower(name) = lower('Red Poncho')), null),
  ((select id from mobs where lower(name) = lower('Spirit Fox')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('Spirit Fox')), (select id from items where lower(name) = lower('Orange Striped Bucket Hat')), null),
  ((select id from mobs where lower(name) = lower('Spirit Fox')), (select id from items where lower(name) = lower('Tan Barbarian Cloak Recipe')), null),
  ((select id from mobs where lower(name) = lower('Shinkai Crab')), (select id from items where lower(name) = lower('See the Drops table below')), null),
  ((select id from mobs where lower(name) = lower('Reyha')), (select id from items where lower(name) = lower('See the Drops table below')), null),
  ((select id from mobs where lower(name) = lower('Wolf')), (select id from items where lower(name) = lower('Canine Fang')), null),
  ((select id from mobs where lower(name) = lower('Wolf')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Wolf')), (select id from items where lower(name) = lower('Red Folded Pants')), null),
  ((select id from mobs where lower(name) = lower('Wolf')), (select id from items where lower(name) = lower('Leather')), null),
  ((select id from mobs where lower(name) = lower('White Tiger')), (select id from items where lower(name) = lower('Tiger Fur')), null),
  ((select id from mobs where lower(name) = lower('White Tiger')), (select id from items where lower(name) = lower('Blank Scroll')), null),
  ((select id from mobs where lower(name) = lower('Wild Rabbit')), (select id from items where lower(name) = lower('Carrot')), null),
  ((select id from mobs where lower(name) = lower('Wild Rabbit')), (select id from items where lower(name) = lower('Rabbit Paw')), null),
  ((select id from mobs where lower(name) = lower('Yuno')), (select id from items where lower(name) = lower('Kazaruu Recipe')), null)
on conflict (mob_id, item_id) do update set
  drop_rate = excluded.drop_rate;
